# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boosty_app', '0002_remove_post_is_published_post_status_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_free',
            field=models.BooleanField(
                default=False, help_text='If True, post is visible to everyone (subscribed and unsubscribed users)'
            ),
        ),
    ]
