# Generated by Django 5.2.7 on 2025-11-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boosty_app", "0003_post_is_free"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into the admin site.",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
            ),
        ),
    ]
