# Generated by Django 5.2.7 on 2025-11-07 10:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boosty_app", "0004_userprofile_is_staff_userprofile_is_superuser"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the tier (e.g., Basic, Premium, VIP)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of what this tier includes",
                        max_length=1000,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly price in USD",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Tier cover image",
                        null=True,
                        upload_to="tier_images/",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (lower number = higher priority)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this tier is available for subscription",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="boosty_app.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["creator", "order", "price"],
                "unique_together": {("creator", "name")},
            },
        ),
        migrations.AddField(
            model_name="post",
            name="tiers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Subscription tiers that can access this post. Leave empty if post is free.",
                related_name="posts",
                to="boosty_app.subscriptiontier",
            ),
        ),
        migrations.CreateModel(
            name="TierSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether subscription is currently active",
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                (
                    "end_date",
                    models.DateTimeField(help_text="When the current subscription period ends"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When user cancelled (still active until end_date)",
                        null=True,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Payment transaction ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="boosty_app.subscriptiontier",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subscriber", "is_active"],
                        name="boosty_app__subscri_d71602_idx",
                    ),
                    models.Index(
                        fields=["tier", "is_active"],
                        name="boosty_app__tier_id_398e84_idx",
                    ),
                ],
            },
        ),
    ]
